services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: MyPass01
       MYSQL_USER: myuser
       MYSQL_DATABASE: spring-master
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: